spring.datasource.url: jdbc:mysql://localhost:3306/tasklib?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
spring.datasource.username: root
spring.datasource.password: Nikel6027Fezel6027
spring.jpa.hibernate.ddl-auto: none
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect